version: '3.3'
services:
  postgres:
    image: postgres:10
    container_name: postgres
    environment:
      - POSTGRES_DB=dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TZ=GMT
    ports:
      - 5432:5432
